-- Небожители
UPDATE `creature_template` SET `faction_A`='35', `faction_H`='35', `unit_flags`='0' WHERE (`entry`='71952');
UPDATE `creature_template` SET `faction_A`='35', `faction_H`='35', `unit_flags`='0' WHERE (`entry`='71953');
UPDATE `creature_template` SET `faction_A`='35', `faction_H`='35', `unit_flags`='0' WHERE (`entry`='71954');
UPDATE `creature_template` SET `faction_A`='35', `faction_H`='35', `unit_flags`='0' WHERE (`entry`='71955');

INSERT INTO `locales_creature_text` (`entry`, `textGroup`, `id`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`, `text_loc9`, `text_loc10`) VALUES ('73303', '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Давным-давно Нефритовая Змея сказала мне, что надо очистить дух и слиться с землей. Так я поборол сомнение.', NULL, NULL);
INSERT INTO `locales_creature_text` (`entry`, `textGroup`, `id`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`, `text_loc9`, `text_loc10`) VALUES ('73303', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Я был силен, но безрассуден. Белый Тигр обучил меня управлять собой. Так я поборол ненависть, злобу и жестокость.', NULL, NULL);
INSERT INTO `locales_creature_text` (`entry`, `textGroup`, `id`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`, `text_loc9`, `text_loc10`) VALUES ('73303', '2', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Красный Журавль увидел во мне надежду и велел заглянуть внутрь себя. Хоть я и чувствовал отчаяние, надежда помогла побороть его.', NULL, NULL);
INSERT INTO `locales_creature_text` (`entry`, `textGroup`, `id`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`, `text_loc9`, `text_loc10`) VALUES ('73303', '3', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Перед лицом великого страха Черный Бык учил меня стойкости. Так я превозмог ужас и тьму, и страх отступил', NULL, NULL);
INSERT INTO `locales_creature_text` (`entry`, `textGroup`, `id`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`, `text_loc9`, `text_loc10`) VALUES ('73303', '4', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Вам удалось пройти испытание мудрости и путь Нефритовой Змеи. Извлеките из них урок, как я когда-то.', NULL, NULL);
INSERT INTO `locales_creature_text` (`entry`, `textGroup`, `id`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`, `text_loc9`, `text_loc10`) VALUES ('73303', '5', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Вам удалось пройти испытание силы и путь Белого Тигра. Запомните этот урок навсегда.', NULL, NULL);
INSERT INTO `locales_creature_text` (`entry`, `textGroup`, `id`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`, `text_loc9`, `text_loc10`) VALUES ('73303', '6', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Вам удалось пройти испытание надежды и путь Красного Журавля. Да направит он ваши стопы.', NULL, NULL);
INSERT INTO `locales_creature_text` (`entry`, `textGroup`, `id`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`, `text_loc9`, `text_loc10`) VALUES ('73303', '7', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Вам удалось пройти испытание стойкости и путь Черного Быка. Да пребудет с вами его благословение!', NULL, NULL);
INSERT INTO `locales_creature_text` (`entry`, `textGroup`, `id`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`, `text_loc9`, `text_loc10`) VALUES ('71954', '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Сейчас увидим!', NULL, NULL);
INSERT INTO `locales_creature_text` (`entry`, `textGroup`, `id`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`, `text_loc9`, `text_loc10`) VALUES ('71954', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Устоите ли вы на вершине вопреки непогоде, пока лес не иссохнет и горы не падут в море?', NULL, NULL);
INSERT INTO `locales_creature_text` (`entry`, `textGroup`, `id`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`, `text_loc9`, `text_loc10`) VALUES ('71954', '2', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Вас будут окружать враги невероятной силы. Большей, чем вы можете представить. Но вы все выдержите благодаря своей стойкости. Помните об этом!', NULL, NULL);
INSERT INTO `locales_creature_text` (`entry`, `textGroup`, `id`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`, `text_loc9`, `text_loc10`) VALUES ('71954', '3', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Больше упорства!', NULL, NULL);
INSERT INTO `locales_creature_text` (`entry`, `textGroup`, `id`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`, `text_loc9`, `text_loc10`) VALUES ('71954', '4', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Ветра сильны, а снег жалит кожу.', NULL, NULL);
INSERT INTO `locales_creature_text` (`entry`, `textGroup`, `id`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`, `text_loc9`, `text_loc10`) VALUES ('71954', '5', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Вы – твердыня, которую ничто не может пошатнуть', NULL, NULL);
INSERT INTO `locales_creature_text` (`entry`, `textGroup`, `id`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`, `text_loc9`, `text_loc10`) VALUES ('71954', '6', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Будьте бдительны, или никогда не добьетесь своего.', NULL, NULL);
INSERT INTO `locales_creature_text` (`entry`, `textGroup`, `id`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`, `text_loc9`, `text_loc10`) VALUES ('71955', '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Начнем схватку!', NULL, NULL);
INSERT INTO `locales_creature_text` (`entry`, `textGroup`, `id`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`, `text_loc9`, `text_loc10`) VALUES ('71955', '1', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Мои дорогие герои, истинная мудрость проявляется в вашем выборе. Столкнувшись с великой тьмой, сможете ли вы принять верное решение?', NULL, NULL);
INSERT INTO `locales_creature_text` (`entry`, `textGroup`, `id`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`, `text_loc9`, `text_loc10`) VALUES ('71955', '2', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Мудрость помогла вам пройти испытание. Пусть она всегда ведет вас к свету.', NULL, NULL);
INSERT INTO `locales_creature_text` (`entry`, `textGroup`, `id`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`, `text_loc9`, `text_loc10`) VALUES ('71955', '3', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Учитесь на ошибках!', NULL, NULL);
INSERT INTO `locales_creature_text` (`entry`, `textGroup`, `id`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`, `text_loc9`, `text_loc10`) VALUES ('71955', '4', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Слушайте внутренний голос и стремитесь к истине!', NULL, NULL);
INSERT INTO `locales_creature_text` (`entry`, `textGroup`, `id`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`, `text_loc9`, `text_loc10`) VALUES ('71955', '5', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Думайте о последствиях своих действий!', NULL, NULL);

